sudo: required
services: 
  - docker

before_install:
  - docker build -t sgriffithkuricor/docker-react -f Dockerfile.dev .

scripts:
  - docker run sgriffithkuricor/docker-react npm run test -- --coverage