sudo: required

services:
  - docker

language: node_js

before_install:
  - docker build -t sgriffithkuricor/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true sgriffithkuricor/docker-react npm run test --coverage